from python_framework import Enum, EnumItem


@Enum(associateReturnsTo='name')
class VoiceEnumeration:

    JENIFER = EnumItem(name='Jennifer')
    KAREN = EnumItem(name='Karen')
    JESSICA = EnumItem(name='Jessica')
    KEVIN = EnumItem(name='Kevin')
    LUCAS = EnumItem(name='Lucas')
    VICTORIA = EnumItem(name='Victoria')

    EDWARD = EnumItem(name='en-US_KevinV3Voice')
    MICHELE = EnumItem(name='en-US-MichelleNeural')
    ALISSON = EnumItem(name='en-US_AllisonV3Voice')
    JENNY = EnumItem(name='en-US-JennyNeural')
    ALLEN = EnumItem(name='en-US-Wavenet-G')
    MICHAEL = EnumItem(name='en-US_MichaelV3Voice')
    OLIVA = EnumItem(name='en-US_OliviaV3Voice')
    AMBER = EnumItem(name='en-US-AmberNeural')
    ANA = EnumItem(name='en-US-AnaNeural')
    ARIA = EnumItem(name='en-US-AriaNeural')
    ASHLEY = EnumItem(name='en-US-AshleyNeural')
    ELIZABETH = EnumItem(name='en-US-ElizabethNeural')
    BRANDON = EnumItem(name='en-US-BrandonNeural')
    FALLEN = EnumItem(name='en-US-Wavenet-H')
    CRISTOPTHER = EnumItem(name='en-US-ChristopherNeural')
    CORA = EnumItem(name='en-US-CoraNeural')
    EMILY = EnumItem(name='en-US_EmilyV3Voice')
    ERIC = EnumItem(name='en-US-EricNeural')
    GUY = EnumItem(name='en-US-GuyNeural')
    HENRY = EnumItem(name='en-US_HenryV3Voice')
    JACOB = EnumItem(name='en-US-JacobNeural')
    FAUTH = EnumItem(name='en-US-Wavenet-A')
    KZAM = EnumItem(name='en-US-Wavenet-D')
    KLAIN = EnumItem(name='en-US-Wavenet-I')
    SARAH = EnumItem(name='en-US-SaraNeural')
    MONICA = EnumItem(name='en-US-MonicaNeural')
    FALY = EnumItem(name='en-US-Wavenet-B')
    GLAM = EnumItem(name='en-US-Wavenet-J')
    LISA = EnumItem(name='en-US_LisaV3Voice')
    JANE = EnumItem(name='en-US-JaneNeural')
    DAVIS = EnumItem(name='en-US-DavisNeural')
    TONY = EnumItem(name='en-US-TonyNeural')
    JASON = EnumItem(name='en-US-JasonNeural')
    NANCY = EnumItem(name='en-US-NancyNeural')

    ANTONIO = EnumItem(name='pt-BR-AntonioNeural')
    CAROLINA = EnumItem(name='pt-BR_IsabelaV3Voice')
    BRENDA = EnumItem(name='pt-BR-BrendaNeural')
    WAVENET = EnumItem(name='pt-BR-Wavenet-B')
    GIOVANNA = EnumItem(name='pt-BR-GiovannaNeural')
    DONATO = EnumItem(name='pt-BR-DonatoNeural')
    ELZA = EnumItem(name='pt-BR-ElzaNeural')
    FABIO = EnumItem(name='pt-BR-FabioNeural')
    HUMBERTO = EnumItem(name='pt-BR-HumbertoNeural')
    JULIO = EnumItem(name='pt-BR-JulioNeural')
    YARA = EnumItem(name='pt-BR-YaraNeural')
    MANUEL = EnumItem(name='pt-BR-ManuelaNeural')

Voice = VoiceEnumeration()
